### PR TITLE
Flutter Package workflows

### PR DESCRIPTION
**Pull request by acpoppe**

### CODE REVIEW

**Review by KlausNie — COMMENTED** [review]
I have no idea what this does, but I'd love to have an exemplary snipped in the README

**Comment by acpoppe** [comment]
> I have no idea what this does, but I'd love to have an exemplary snipped in the README

I added some examples and overviews of them as the first documentation in this repo, just for you! :)

**Comment by KlausNie** [comment]
Is this already somewhere used?

**Comment by acpoppe** [comment]
> Is this already somewhere used?

I tested it here https://github.com/QuickBirdEng/qb-public-key-pinning-flutter. (Obviously still pointing to this branch rather than main, otherwise everything is as it should be)

**Pull request merged**
